function [G] = SVDLVM(n)
%Author: Zachary

%Returns nxn rank 2 non-symmetric matrix generated by a latent variable
%model. Used for testing SVD approach

u2 = @(x) exp(-x.^2);
v1 = @(x) exp(-x);
v2 = @(x) (sin(x)).^2;
theta = unifrnd(0,1,n);
Lambda = diag(unifrnd(0,1,2,1));
U = zeros(2,n); V = zeros(2,n);
for i = 1:1:n
    U(1,i) = 1;
    U(2,i) = u2(theta(i));
    V(1,i) = v1(theta(i));
    V(2,i) = v2(theta(i));
end
F = U'*Lambda*V;
G = F/max(max(abs(F)));